### ISSUE TITLE
Report progress of individual test cases

### ISSUE THREAD

**Issue by jevakallio** [MLH-Fellowship/jest#1]
## Start point for the problem

- [x] Allow jest-worker to send custom messages back to the main process so that we can notify when a test case is done.
- [x] Builds on top of @SimenB's approach of using an event emitter for this in the TestScheduler side.https://github.com/facebook/jest/issues/6616#issuecomment-402782271
- [x] Implements the API that @rickhanlonii suggested https://github.com/facebook/jest/issues/6616#issuecomment-402782271
- [x] Update the reporter and Status to handle the test case result.

The above issues were tackled, but still under review/progress as mentioned in the PR https://github.com/facebook/jest/pull/9001.

## Continued issues

The original PR https://github.com/facebook/jest/pull/9001 mentioned above has been kinda stale for some time. So we get started by -
- [ ] Currently, this PR has a mix of both `eventEmitters` and `callbacks` to  jest-circus. **I suggest we go for `eventEmitters` only solution**. Although the project currently handles communication via callbacks, as discussed in here: https://github.com/facebook/jest/issues/6616#issuecomment-414115878 and mentioned by Simen in the call itself, it is eventually planned to shift to emitters.

    This can be an experimental API, so doesn't become a breaking change (if this gets accepted). 
    Something like
    ```typescript
    testRunnter.__EXPERIMENTAL_supportsEventEmmiters__
    ```
   _(Though I don't have much idea, how to shift the current callbacks methods to eventEmitters, as it will create a sequence of changes. We might stick to current methods, if implementing eventEmitters is getting hard, maybe create a separate issue for it. Someone could help here)_

- [ ] Wrapping up the custom message emit from the `testReporter`.
  - [ ] Currently has a single custom message `.onCustomMessage(cb)` extended on the interface for the `Reporter` [Refer BaseReporter class]. It can be split up into
        `onTestRun` - all _files_ in all _runners_
        `onTestFile` - one _file_
        `onTest` - one _test/it_
        `onDescribeBlock` - one _describe_
        `onAssertion` - one _expect_ call <br>
         as discussed in the issue https://github.com/facebook/jest/issues/6616#issuecomment-403899521

Would be great if someone shared or added thoughts on this 😅

**Comment by sauravhiremath** [comment]
@jevakallio @kunal-kushwaha would be great if any suggestions or changes added to this :D

**Comment by kunal-kushwaha** [comment]
I believe this is a good start:
https://github.com/facebook/jest/pull/9662 is a breakdown for https://github.com/facebook/jest/pull/9001

**Comment by sauravhiremath** [comment]
> I believe this is a good start:
> [facebook#9662](https://github.com/facebook/jest/pull/9662) is a breakdown for [facebook#9001](https://github.com/facebook/jest/pull/9001)

Yeah I went through this PR yesterday and implemented the same on my local machine, it did achieve the goals listed on the PR. There were some reviews left by Simen there.

Though they weren't responded by the PR author, should we mention on the original PR facebook#9662 that we would be continuing from that, and add subsequent progress to facebook#9001 ? @jevakallio 

Edit: It didn't seem right, coz @rogeliog has worked a lot since Oct 19 (afaik). So ...

**Comment by kunal-kushwaha** [comment]
PR merged 🎉
